apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: sno
rendezvousIP: 10.0.30.50
additionalNTPSources:
  - 10.0.10.1
hosts:
  - hostname: sno
    role: master
    interfaces:
      - name: ens18
        macAddress: bc:24:11:df:af:4d
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: bc:24:11:df:af:4d
          ipv4:
            enabled: true
            dhcp: false
            address:
              - ip: 10.0.30.50
                prefix-length: 24
          ipv6:
            enabled: false
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.0.30.1
            next-hop-interface: ens18
      dns-resolver:
        config:
          server:
            - 10.0.10.4
          search: []
