apiVersion: v1
baseDomain: chkpwd.com
compute:
  - name: worker
    replicas: 0
    architecture: amd64
controlPlane:
  name: master
  replicas: 1
  architecture: amd64
metadata:
  name: sno
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: "REPLACE_WITH_PULL_SECRET"
sshKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJPp2amKRc/zpXzG9Xo0drbXCM2/PSQ4XgLHhQONHLBm core@sno.chkpwd.com"
