---
# yaml-language-server: $schema=https://chkpwd.github.io/iac/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: towonel-agent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: towonel-agent
  values:
    replicaCount: 2
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    agent:
      logLevel: info
      healthPort: 9090
      services:
        - hostname: echo.chkpwd.com
          origin: echo.networking.svc.cluster.local:8080
          proxy_protocol: none
      inviteTokenSecret:
        name: towonel-agent-secret
        key: TOWONEL_INVITE_TOKEN
    monitoring:
      serviceMonitor:
        enabled: true
        interval: 1m
      prometheusRule:
        enabled: true
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          allowCrossNamespaceImport: true
          matchLabels:
            grafana.internal/instance: grafana
