---
common_user: chkpwd
ansible_user: chkpwd
docker_users: "{{ common_user }}"
docker_daemon_options:
  data-root: /mnt/data/docker
service_definitions:
  - name: nginx_webserver
    image: nginx:1.25.4-alpine3.18-slim
    ports:
      - 8081:80
    volumes:
      - "{{ compose_configuration_path }}/nginx_webserver/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "{{ compose_configuration_path }}/nginx_webserver/files:/files"
    state: stopped
  - name: scanservjs
    image: sbs20/scanservjs:v3.0.4
    ports:
      - 8087:8080
    env:
      DEVICES: "airscan:e0:Epson ET-2850;escl:https://10.0.30.8:443"
      PAPERLESS_URL: "https://paperless-ngx.{{ domain }}"
      PAPERLESS_API_TOKEN: "{{ lookup('ripplefcl.bwscache.secret', 'ns-tools-paperless-ngx').value.token }}"
      PAPERLESS_DELETE_AFTER_UPLOAD: "true"
    volumes:
      - "{{ compose_configuration_path }}/scanservjs/output:/var/lib/scanservjs/output"
      - "{{ compose_configuration_path }}/scanservjs:/etc/scanservjs"
    networks:
      - name: "proxy"
    labels:
      traefik.enable: "true"
      traefik.http.routers.scanservjs.rule: "Host(`scan.chkpwd.com`)"
      traefik.http.routers.scanservjs.entrypoints: "https"
      traefik.http.services.scanservjs.loadbalancer.server.port: "8080"
      traefik.http.routers.scanservjs.tls: "true"
      traefik.http.routers.scanservjs.tls.certresolver: cloudflare
      traefik.http.routers.scanservjs.tls.domains[0].main: chkpwd.com
      traefik.http.routers.scanservjs.tls.domains[0].sans: "*.chkpwd.com"
    dns_servers:
      - 10.0.10.4
  - name: dyrne
    image: ghcr.io/overengineers-anonymous/dyrne
    ports: ["5001:5000"]
  - name: bws-cache
    image: ghcr.io/ripplefcl/bws-cache:v3.2.2
    env:
      PARSE_SECRET_VALUES: "true"
      LOG_LEVEL: "warning"
      ENABLE_TELEMETRY: "true"
      SENTRY_ENVIRONMENT: "chkpwd"
    ports: ["5000:5000"]
