---
# yaml-language-server: $schema=https://chkpwd.github.io/iac/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: dawarich
    template:
      engineVersion: v2
      data:
        SECRET_KEY_BASE: "{{ .secret_key_base }}"
        OTP_ENCRYPTION_PRIMARY_KEY: "{{ .otp_encryption_primary_key }}"
        OTP_ENCRYPTION_DETERMINISTIC_KEY: "{{ .otp_encryption_deterministic_key }}"
        OTP_ENCRYPTION_KEY_DERIVATION_SALT: "{{ .otp_encryption_key_derivation_salt }}"
  dataFrom:
    - extract:
        key: dawarich
