{
 "title": "Storage Ceph Usage",
 "description": "Ceph usage by device class, osd and pool",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "device_class",
    "query": {
     "query": "label_values(ceph_osd_metadata,device_class)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "total size by device class",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (device_class) (ceph_osd_stat_bytes * on (ceph_daemon) group_left(device_class) ceph_osd_metadata{device_class=~\"$device_class\"})",
     "legendFormat": "{{device_class}}"
    }
   ]
  },
  {
   "title": "used by pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (name) (ceph_pool_stored * on(pool_id) group_left(name) ceph_pool_metadata)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "total used by device class",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (device_class) (ceph_osd_stat_bytes_used * on (ceph_daemon) group_left(device_class) ceph_osd_metadata{device_class=~\"$device_class\"})",
     "legendFormat": "{{device_class}}"
    }
   ]
  },
  {
   "title": "total used by osd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_osd_stat_bytes_used * on (ceph_daemon) ceph_osd_metadata{device_class=~\"$device_class\"})",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "total used by device class (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (device_class) (ceph_osd_stat_bytes_used / on (ceph_daemon) group_left(device_class) ceph_osd_metadata{device_class=~\"$device_class\"}) / sum by (device_class) (ceph_osd_stat_bytes / on (ceph_daemon) group_left(device_class) ceph_osd_metadata{device_class=~\"$device_class\"})",
     "legendFormat": "{{device_class}}"
    }
   ]
  },
  {
   "title": "total used by osd (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(ceph_osd_stat_bytes_used / on (ceph_daemon) ceph_osd_metadata{device_class=~\"$device_class\"}) / (ceph_osd_stat_bytes / on (ceph_daemon) ceph_osd_metadata{device_class=~\"$device_class\"})",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  }
 ]
}