---
# yaml-language-server: $schema=https://chkpwd.github.io/iac/cilium.io/ciliumbgpclusterconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: "cilium"
      localASN: 64513
      peers:
        - name: "mikrotik"
          peerASN: 64512
          peerAddress: 10.0.10.1
          peerConfigRef:
            name: peer-mikrotik
---
# yaml-language-server: $schema=https://chkpwd.github.io/iac/cilium.io/ciliumbgppeerconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: peer-mikrotik
spec:
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
# yaml-language-server: $schema=https://chkpwd.github.io/iac/cilium.io/ciliumbgpadvertisement_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: "bgp"
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
