---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium
  namespace: &ns kube-system
spec:
  targetNamespace: *ns
  path: ./kubernetes/core/cilium/
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  postBuild:
    substitute:
      APP: hubble
      RECORD_NAME: hubble
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cilium
      namespace: *ns
  prune: false
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
    namespace: flux-system
  wait: true
  interval: 15m
  retryInterval: 2m
  timeout: 5m
