---
# yaml-language-server: $schema=https://chkpwd.github.io/iac/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: 1.19.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
