---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yml
  - bgp.yml
  - pools.yml
  - source.yml
  - http-route.yml
  - netpols/media-clients-cidr.yml
  - netpols/allow-dns-egress.yml
  - netpols/allow-cluster-egress.yml
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=./values.yml
configurations:
  - ./kustomizeconfig.yml
