apiVersion: v1
kind: Secret
metadata:
  name: k10-s3-bucket1-creds
  namespace: kasten-io
type: Opaque
stringData:
  aws_access_key_id: REPLACE_WITH_ACCESS_KEY_ID
  aws_secret_access_key: REPLACE_WITH_SECRET_ACCESS_KEY
