---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: namespaces
  namespace: flux-system
spec:
  inputs:
    - name: actions-runner-system
    - name: ai
    - name: databases
    - name: media
    - name: monitoring
    - name: networking
    - name: rook-ceph
    - name: runners
    - name: security
    - name: storage
    - name: system
    - name: tools
    - name: crd-schema-publisher
  resourcesTemplate: |
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      name: << inputs.name >>
      annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
        << if or (eq inputs.name "media") (eq inputs.name "tools") >>
        volsync.backube/privileged-movers: "true"
        << end >>
