---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: isponsorblocktv
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: isponsorblocktv
    template:
      engineVersion: v2
      data:
        config.json: |
          {
            "devices": [
                {
                  "screen_id": "{{ .isb_screen_id_1 }}",
                  "name": "tv-tlc-01",
                  "offset": 0
                }
            ],
            "apikey": "",
            "skip_categories": [
                "sponsor",
                "selfpromo",
                "exclusive_access",
                "interaction",
                "poi_highlight",
                "intro",
                "outro",
                "preview",
                "filler"
            ],
            "channel_whitelist": [],
            "skip_count_tracking": false,
            "mute_ads": true,
            "skip_ads": true
          }
  dataFrom:
    - extract:
        key: "isponsorblocktv"
