# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.5.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: isponsorblocktv
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  values:
    controllers:
      main:
        pod:
          terminationGracePeriodSeconds: 1
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: {type: RuntimeDefault}
        containers:
          main:
            image:
              repository: ghcr.io/dmunozv04/isponsorblocktv
              tag: v2.6.1
              pullPolicy: IfNotPresent
            env:
              TZ: America/Chicago
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: [ALL]}
    persistence:
      config:
        enabled: true
        type: secret
        name: isponsorblocktv
        globalMounts:
          - path: /app/data/config.json
            subPath: config.json
            readOnly: true
