---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/mutatingadmissionpolicy-admissionregistration-v1beta1.json
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicy
metadata:
  name: volsync-mover-shuffle
  namespace: storage
spec:
  matchConstraints:
    resourceRules:
      - apiGroups:
          - batch
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - jobs
  matchConditions:
    - name: has-volsync-job-name-prefix
      expression: >-
        object.metadata.name.startsWith("volsync-src-")
    - name: has-volsync-created-by-labels
      expression: >-
        object.metadata.?labels["app.kubernetes.io/created-by"].orValue("") == "volsync"
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression:
          >- # write random permutation to the startup of the volsync mover pod to avoid all jobs initiating at the same time
          [
            JSONPatch{
              op: "add", path: "/spec/template/spec/initContainers",
              value: []
            },
            JSONPatch{
              op: "add", path: "/spec/template/spec/initContainers/-",
              value: Object.spec.template.spec.initContainers{
                name: "shuffle",
                image: "busybox:1.37.0",
                imagePullPolicy: "IfNotPresent",
                command: ["sh", "-c", "sleep $(shuf -i 0-150 -n 1)"]
              }
            }
          ]
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/mutatingadmissionpolicybinding-admissionregistration-v1beta1.json
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: volsync-mover-shuffle
spec:
  policyName: volsync-mover-shuffle
