---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app booklore
  namespace: &ns media
spec:
  targetNamespace: *ns
  path: ./kubernetes/apps/booklore/
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../core/volsync/components/
    - ../../core/keda-operator/_components/nfs/
  postBuild:
    substitute:
      APP: *app
      CLAIM: config-booklore-0
      VOLSYNC_UID: "1999"
      VOLSYNC_GID: "1999"
      VOLSYNC_CAPACITY: "2Gi"
  patches:
    - patch: |
        - op: replace
          path: /spec/kopia/retain
          value:
            daily: 14
            weekly: 8
            monthly: 6
      target:
        kind: ReplicationSource
        name: booklore
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
    namespace: flux-system
  wait: false
  interval: 30m
