---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sample-httproute.yaml
  - private-gateway.yaml
bases:
  - https://github.com/kubernetes-sigs/gateway-api/tree/main/config/crd/standard
