---
# yaml-language-server: $schema=https://chkpwd.github.io/iac/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-mcp-reporter-webhook
spec:
  refreshInterval: 168h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: flux-mcp-reporter-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: flux-mcp-reporter
        property: webhook_url
