---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: private
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: private
      sectionName: https
  clientIPDetection:
    xForwardedFor:
      trustedCIDRs: ["10.244.0.0/16"]
  http2:
    onInvalidMessage: TerminateStream
  tls:
    alpnProtocols:
      - http/1.1
      - h2
    minVersion: "1.2"
    maxVersion: "1.3"
    ciphers:
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-CHACHA20-POLY1305
    ecdhCurves:
      - X25519
      - P-256
    signatureAlgorithms:
      - ecdsa_secp256r1_sha256
      - ecdsa_secp384r1_sha384
      - ecdsa_secp521r1_sha512
      - ed25519
    clientValidation:
      optional: true
  connection:
    bufferLimit: 8Mi
  tcpKeepalive: {}
  timeout:
    http:
      requestReceivedTimeout: 3600s
  headers:
    enableEnvoyHeaders: false
    disableRateLimitHeaders: true
    lateResponseHeaders:
      remove:
        - Server
        - X-Powered-By
        - X-AspNet-Version
        - X-AspNetMvc-Version
      set:
        - name: Strict-Transport-Security
          value: "max-age=31449600; includeSubDomains; preload"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: public
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public
      sectionName: https
  clientIPDetection:
    xForwardedFor:
      trustedCIDRs: ["10.244.0.0/16"]
  http2:
    onInvalidMessage: TerminateStream
  tls:
    alpnProtocols:
      - http/1.1
      - h2
    minVersion: "1.2"
    maxVersion: "1.3"
    ciphers:
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-CHACHA20-POLY1305
    ecdhCurves:
      - X25519
      - P-256
    signatureAlgorithms:
      - ecdsa_secp256r1_sha256
      - ecdsa_secp384r1_sha384
      - ecdsa_secp521r1_sha512
      - ed25519
    clientValidation:
      optional: true
  connection:
    bufferLimit: 100Ki
    socketBufferLimit: 1Mi
  tcpKeepalive:
    interval: 10s
    idleTime: 10s
  timeout:
    http:
      requestReceivedTimeout: 10s
  headers:
    enableEnvoyHeaders: false
    disableRateLimitHeaders: true
    lateResponseHeaders:
      remove:
        - Server
        - X-Powered-By
        - X-AspNet-Version
        - X-AspNetMvc-Version
      set:
        - name: Strict-Transport-Security
          value: "max-age=31449600; includeSubDomains; preload"
        - name: X-Robots-Tag
          value: "noindex, nofollow"
        - name: X-Frame-Options
          value: DENY
        - name: X-Content-Type-Options
          value: nosniff
        - name: X-XSS-Protection
          value: "1; mode=block"
        - name: Referrer-Policy
          value: no-referrer
        - name: X-DNS-Prefetch-Control
          value: "off"
        - name: Permissions-Policy
          value: "interest-cohort=()"
        - name: Cross-Origin-Opener-Policy
          value: same-origin
        - name: Cross-Origin-Resource-Policy
          value: same-site
        - name: Cross-Origin-Embedder-Policy
          value: require-corp
