---
# yaml-language-server: $schema=https://chkpwd.github.io/iac/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${CLAIM:=${APP}}"
  trigger:
    schedule: 30 2 * * *
  kopia:
    repository: "${APP}-volsync"
    copyMethod: Snapshot
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=4Gi}"
    cacheStorageClassName: ceph-block
    cacheAccessModes: ["ReadWriteOnce"]
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /volume1/vault-01/backups/kubernetes/volsync/kopia
            server: nas-srv-01.chkpwd.com
    moverSecurityContext:
      runAsUser: ${VOLSYNC_UID:=1000}
      runAsGroup: ${VOLSYNC_GID:=100}
      fsGroup: ${VOLSYNC_GID:=100}
    compression: zstd-fastest
    parallelism: 2
    retain:
      hourly: 10
      daily: 7
      weekly: 4
      monthly: 3
    policyConfig:
      repositoryConfig: |-
        {
          "errorHandling": {
            "ignoreFileErrors": false,
            "ignoreDirectoryErrors": false,
            "ignoreUnknownTypes": true
          },
          "files": {
            "ignore": ["lost+found/"],
            "ignoreCacheDirs": true,
            "dotFiles": "include",
            "oneFileSystem": true
          }
        }
