---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    server:
      root_url: "https://grafana.chkpwd.com"
    auth:
      disable_login_form: "false"
    security:
      cookie_secure: "true"
  persistentVolumeClaim:
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ceph-block
      resources:
        requests:
          storage: "${VOLSYNC_CAPACITY}"
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator
                      key: GF_SECURITY_ADMIN_USER
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator
                      key: GF_SECURITY_ADMIN_PASSWORD
              readinessProbe:
                failureThreshold: 3
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
  service:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
  httpRoute:
    spec:
      parentRefs:
        - name: public
          namespace: networking
          sectionName: https
      hostnames:
        - grafana.chkpwd.com
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: "http://prometheus-prometheus.monitoring.svc.cluster.local:9090"
    jsonData:
      timeInterval: 5s
      prometheusType: Prometheus
      cacheLevel: Low
      manageAlerts: true
      httpMethod: POST
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: teslamate-postgres
spec:
  valuesFrom:
    - targetPath: "datasource.url"
      valueFrom:
        secretKeyRef:
          name: teslamate-db-credentials
          key: host
    - targetPath: "datasource.user"
      valueFrom:
        secretKeyRef:
          name: teslamate-db-credentials
          key: user
    - targetPath: "datasource.database"
      valueFrom:
        secretKeyRef:
          name: teslamate-db-credentials
          key: dbname
    - targetPath: "secureJsonData.password"
      valueFrom:
        secretKeyRef:
          name: teslamate-db-credentials
          key: password
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: TeslaMate
    type: postgres
    uid: TeslaMate
    access: proxy
    url: "$${host}"
    database: "$${dbname}"
    user: "$${user}"
    jsonData:
      "sslmode": require
      "maxOpenConns": 100
      "maxIdleConns": 100
      "maxIdleConnsAuto": true
      "connMaxLifetime": 14400
      "postgresVersion": 1600
      "timescaledb": false
    secureJsonData:
      "password": "$${password}"
