---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-schema-publisher
  namespace: crd-schema-publisher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-schema-publisher
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-schema-publisher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-schema-publisher
subjects:
  - kind: ServiceAccount
    name: crd-schema-publisher
    namespace: crd-schema-publisher
