---
# yaml-language-server: $schema=https://chkpwd.github.io/iac/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crd-schema-publisher
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: crd-schema-publisher-git-push
    template:
      engineVersion: v2
      data:
        github-token: "{{ .git_token }}"
        github-repo: "chkpwd/iac"
  dataFrom:
    - extract:
        key: "crd-schema-publisher"
